// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResturantBooking.Data;

#nullable disable

namespace ResturantBooking.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250905101228_NewTableName")]
    partial class NewTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResturantBooking.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "testhash123",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ResturantBooking.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId_FK")
                        .HasColumnType("int");

                    b.Property<int>("Guest")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableId_FK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId_FK");

                    b.HasIndex("TableId_FK");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ResturantBooking.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNbr")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lasse Ricardo",
                            PhoneNbr = "0703873563"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alfie Smith",
                            PhoneNbr = "0765376534"
                        });
                });

            modelBuilder.Entity("ResturantBooking.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Klassisk pizza med mozzarella",
                            IsPopular = true,
                            Name = "Pizza Margherita",
                            Price = 99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sallad med kyckling och parmesan",
                            IsPopular = false,
                            Name = "Caesarsallad",
                            Price = 120m
                        });
                });

            modelBuilder.Entity("ResturantBooking.Models.ResturantTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ResturantTables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 6,
                            Number = 3
                        });
                });

            modelBuilder.Entity("ResturantBooking.Models.Booking", b =>
                {
                    b.HasOne("ResturantBooking.Models.Customer", "Customer")
                        .WithMany("Bokkings")
                        .HasForeignKey("CustomerId_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResturantBooking.Models.ResturantTable", "Table")
                        .WithMany("Bookings")
                        .HasForeignKey("TableId_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("ResturantBooking.Models.Customer", b =>
                {
                    b.Navigation("Bokkings");
                });

            modelBuilder.Entity("ResturantBooking.Models.ResturantTable", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
